### ISSUE TITLE
Linking views and dependencies

### ISSUE THREAD

**Issue by saifulkhan** [ScottishCovidResponse/rampvis-ui#1]
**1. Linking overview and detail pages, e.g., see Alfie's top-level overview screen view**

[a](http://vis.scrc.uk/scotland/overviews/top-level-overview-screen-a.html) -> [b](http://vis.scrc.uk/scotland/regional-overview/sco-regional.html) -> [c](http://vis.scrc.uk/scotland/detailed/sco-icupatients.html)

or 

[a] -> [d](http://vis.scrc.uk/scotland/detailed/sco-cumulative.html)

**2. Min/Max**

**Comment by alfieabdulrahman** [comment]
We solved Point (1), but Point (2) Min/Max is still not solved.
