### ISSUE TITLE
Table pagination

### ISSUE THREAD

**Issue by saifulkhan** [ScottishCovidResponse/rampvis-ui#105]
e.g., https://vis.scrc.uk/plot

**Comment by kachkaev** [comment]
What do we want to change about pagination?

**Comment by saifulkhan** [comment]
Actually currently the page is fetching table data from https://vis.scrc.uk/api/v1/template/pages/all/plot and it takes a time to load all data. Ideally the page should call paginated data using pageIndex and pageSize as query parameter, e.g., https://vis.scrc.uk/api/v1/template/pages/all/plot /?pageIndex=0&pageSize=50 . I don't know how to do that in React.
