### ISSUE TITLE
Use arrow function and rollback the .eslint changes for _this

### ISSUE THREAD

**Issue by saifulkhan** [ScottishCovidResponse/rampvis-ui#115]
In https://github.com/ScottishCovidResponse/rampvis-ui/blob/nextjs-migrate/src/components/ensemble/controller.js#L99 use an arrow function and rollback the changes in the .eslistrc.  Please see the conversation https://app.slack.com/client/T028UQMPP1P/C02NDS0GQFK or reply there if you need anything, @kamakshidasan.

**Comment by kamakshidasan** [comment]
@saifulkhan @phongvis I have completed this and merged my branch.

In doing so, I found that "src/utils/apiService" had become "src/utils/ApiService". I reverted that and changed the import statements.
