### ISSUE TITLE
Broken page - Coronavirus (COVID-19): Scotland Board-level Daily Data

### ISSUE THREAD

**Issue by alfieabdulrahman** [ScottishCovidResponse/rampvis-ui#13]
The page should look like this:

<img width="1408" alt="Screenshot 2020-07-13 at 12 09 31" src="https://user-images.githubusercontent.com/1651996/87298243-c5a84580-c501-11ea-870f-03cc0d86aecc.png">

**Comment by saifulkhan** [comment]
Please check- 

https://github.com/ScottishCovidResponse/rampvis-ui/commit/3c2ec9cfb2f46f51557fbb65f34c5a5187691bc9

**Comment by alfieabdulrahman** [comment]
It is fine but we are missing the data for the Golden Jubilee National Hospital.

**Comment by saifulkhan** [comment]
@alfieabdulrahman 

What is the reason behind the two board objects in the files below are different?

https://github.com/ScottishCovidResponse/rampvis-ui-v0.1/blob/master/assets/js/vis/top-level-overview-screen-a.js
https://github.com/ScottishCovidResponse/rampvis-ui-v0.1/blob/master/assets/js/vis/top-level-overview-screen-b.js
