### ISSUE TITLE
Port Visualization - Confirmed COVID-19 cases per NHS board

### ISSUE THREAD

**Issue by alfieabdulrahman** [ScottishCovidResponse/rampvis-ui#23]
Port http://vis.scrc.uk/scotland/overviews-ben/scotmap-cases.html into the new platform.

**Comment by saifulkhan** [comment]
The main files are added it requires further debugging and modularization of the code to make it work.

Please see the branch - https://github.com/ScottishCovidResponse/rampvis-ui/tree/porting-scotmap-charts
