### ISSUE TITLE
Port Visualization - Patients in hospital with suspected Covid

### ISSUE THREAD

**Issue by alfieabdulrahman** [ScottishCovidResponse/rampvis-ui#26]
Port http://vis.scrc.uk/scotland/overviews-ben/scotmap-hospsuspected.html into the new platform.

**Comment by saifulkhan** [comment]
The main files are added it requires further debugging and modularization of the code to make it work.

Please see the branch - https://github.com/ScottishCovidResponse/rampvis-ui/tree/porting-scotmap-charts
