### ISSUE TITLE
Bookmarks in chord diagrams are highlighted (although they are not bookmarked)

### ISSUE THREAD

**Issue by alfieabdulrahman** [ScottishCovidResponse/rampvis-ui#27]
The bookmarks in the chord diagrams are constantly highlighted although they are not bookmarked.

**Comment by saifulkhan** [comment]
@alfieabdulrahman Updated the API and probably fixed. Could you please check this and other pages?

**Comment by alfieabdulrahman** [comment]
It is now fixed.
