### ISSUE TITLE
Change command panel (left-hand navigation)

### ISSUE THREAD

**Issue by phongvis** [ScottishCovidResponse/rampvis-ui#31]
- [x] **On the command panel, there should be buttons:**
- My portal
- Search
- Dashboards
- Plots
- England
- N. Ireland
- Scotland
- Wales
- Analytics
- Dynamic

- [x] **Commands are easy to implement.**
- Search -> show a search interface (optional, with initially all dashboards and plots)
- All dashboards -> show show a search interface with a list of all dashboards
- The rest can easily be inferred.
- All you need to do is to either (perform a search with a predefined set of keywords for each command) or (use a housekeeping agent to precompile a list).

- [x] **About login:**
- Only when one clicks my "Portal" or "Save to my Portal", the system asks for Login.
- The command bar should also show something if a person has logged in.

- [ ] **Note:**
- We may add other categories in the future.
- The dynamics is added temporary for easy to demo.
- Analytics should include all visualizations for the derived data.

**Comment by saifulkhan** [comment]
A couple of them are addressed but should be reviewed again.
