### ISSUE TITLE
Capture thumbnails

### ISSUE THREAD

**Issue by phongvis** [ScottishCovidResponse/rampvis-ui#35]
>     The UI design meeting a few week's ago included a thumbnail feature for
>     personal portal and possibly search. Basically each URL will have a
>     thumbnail stored in the ontology, and the UI for the portal and search
>     can simply reuse the store the thumbnail again and again.
>
>     They would like ideally have an automated process:
>
>     -----------------------------------------------------------------------
>     For each URL in the ontology, there is always a default thumbnail
>     image,
>     saying RAMP VIS. Copy the style of Amazon default.
>
>     A housekeeping program (a parameter for "update-all", or
>     "update-default-only") does the following
>
>     For each page in the ontology
>         If parameter == "update-all" OR
>         the thumbnail == "default.jpg" then
>         begin
>           1. Open a URL
>           2. Take a screen shot (perhaps after some time delay)
>           3. Automatic crop
>           4. Automatic downsize to a low-res thumbnail
>           5. Store it or its link to the ontology
>         end if
>     end for

[UI.pptx](https://github.com/ScottishCovidResponse/rampvis-ui/files/4977296/UI.pptx)

**Comment by phongvis** [comment]
Other comments from Min:

You can also use two different resolutions for cropping dashboard thumbnails and plot thumbnails to give different impression of the scale.

For example a dashboard be cropped as 1200 x 800, while a plot as 600 x 400.

They are both downsized to the thumbnails of the same size

**Comment by phongvis** [comment]
The amazon's image-based listing, i.e., for the recommended products under each web page may not be a bad size or format. The only thing is that it is slightly difficult to calculate a 2D layout. Amazon's one is 1D. Google image is a 2D layout varying according to the screen size.

The amazon's image-based listing has 3 lines of text for each product, and use ... at the end if it is too long.

The image size for the normal product search at Amazon is too big.

Some shopping basket designs may also be suitable.

**Comment by saifulkhan** [comment]
Manual option is added.
