### ISSUE TITLE
[dashboard-request] Country-ages

### ISSUE THREAD

**Issue by benjbach** [ScottishCovidResponse/rampvis-ui#58]
name of dashboard
* Country Data By Age Groups

description of the dashboard
* Different covid data per age groups.

dashboard JS filename
* dashboard-country-ages.js

specific datastreams to include (which file, which URL, you can link to your spreadsheet if you want)
* https://www.opendata.nhs.scot/dataset/6dbdd466-45e3-4348-9ee3-1eac72b5a592/resource/42f17a3c-a4db-4965-ba68-3dffe6bca13a/download/daily_vacc_scot_20210514.csv
* https://www.opendata.nhs.scot/dataset/covid-19-in-scotland/resource/9393bd66-5012-4f01-9bc5-e7a10accacf4
* https://www.opendata.nhs.scot/no/dataset/weekly-covid-19-statistical-data-in-scotland/resource/80f673db-a9b5-4024-8049-c9ee27642904

**Comment by phongvis** [comment]
http://localhost:5000/6113da6097a136112fd842e0

- [x] vaccination
- [ ] cases
- [ ]

**Comment by benjbach** [comment]
Thanks! It's currently only having the vaccinations. Let me know when cases and admissions are added.

**Comment by phongvis** [comment]
@benjbach please have a look at the updated checkbox list above and let me know which ones you want to have. I don't mind getting all. It's pretty quick for the country-level data after identifying those URLs.
