### ISSUE TITLE
[dashboard-request] council-ages

### ISSUE THREAD

**Issue by benjbach** [ScottishCovidResponse/rampvis-ui#60]
name of dashboard
* Council Data by Ages Groups

description of the dashboard
* Different data per age groups on council level

dashboard JS filename
* dashboard-council-ages.js

specific datastreams to include (which file, which URL, you can link to your spreadsheet if you want)
* https://www.opendata.nhs.scot/dataset/6dbdd466-45e3-4348-9ee3-1eac72b5a592/resource/d5ffffc0-f6f3-4b76-8f38-71ccfd7747a4/download/daily_vacc_la_20210514.csv

**Comment by phongvis** [comment]
http://localhost:5000/6113d63e97a136112fd842de

Same comment as in the health board one, feel free to suggest more sex/age data from opendata.

**Comment by benjbach** [comment]
Same comment than for NHS board. We seem to have only vaccination and those data are already in the respective council board. So, let's close and remove this board.
