### ISSUE TITLE
Migrating mirrored plots

### ISSUE THREAD

**Issue by phongvis** [ScottishCovidResponse/rampvis-ui#62]
- [ ] bar http://localhost:5000/611ed55eab48ad430afaa264, old code: `mirrored-stacked-bar-chart.js`, new code: `new-mirrored-stacked-bar-chart.js`
- [ ] area http://localhost:5000/611ed592aced0441afd326c9, old code: `mirrored-stacked-area-chart.js`, new code: `new-mirrored-stacked-area-chart.js`

This is a bit tricky to handle the data. There are 14 data streams in the input for 2 genders x 7 age groups. You might need to group them to 2 gender groups to pass the data to the base vis. However, please make sure you don't access the data using 'gender' or 'agegroup' keys. Access the data in a generic way because it's supposed to work for other data streams with similar structure.

**Comment by phongvis** [comment]
@yuleifan @saifulkhan I will reassign it to me. Yulei please help Saiful with the new React framework

**Comment by saifulkhan** [comment]
I guess it is done, @phongvis ?

**Comment by phongvis** [comment]
yes
